# Site settings
title:       Stuart Baker
email:       bakermstuart@gmail.com
author:      Stuart Baker
description: "description of site, from _config.yml"
baseurl:     ""
url:         "http://smbkr.github.io"
date_format: "%Y-%m-%d"

# Collections
collections:
  photos:
    # output: true
    # permalink: /photos/:path/

# Google services
google_analytics: UA-69610877-1
google_verification: RjfxX1og9_duTvO7eVjw0SfCC-OYoP5R-bRZSHkB6VE

# Optional features
animated:             true
ajaxify_contact_form: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
# paginate:     4
sass:
  compressed: true
exclude: [Gemfile, Gemfile.lock]
timezone: Europe/London
gems:
  - jekyll-sitemap