# Site settings
title:       smbkr.com
email:       bakermstuart@gmail.com
author:      Stuart Baker
description: "description of site, from _config.yml"
baseurl:     ""
url:         "http://smbkr.github.io/"
date_format: "%b %-d, %Y"

# Collections
collections:
  photos:
    # output: true
    # permalink: /photos/:path/

# Google services
google_analytics:
google_verification:

# Optional features
animated:             true
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username:
bitbucket_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: false
gems:
    - jekyll-minifier
exclude: [Gemfile, Gemfile.lock, LICENSE.txt, Rakefile]
timezone: Europe/London
